FROM maven:3.6.3-jdk-11

ENV CLIENT_ID=$GOOGLE_CLIENT_ID

ENV CLIENT_SECRET=$GOOGLE_CLIENT_SECRET

COPY . .

EXPOSE 8080

RUN mvn package

CMD ["java", "-jar", "/target/employeeV11-0.0.1-SNAPSHOT.jar"]