on:
  push:
    branches:
      - git-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: set Maven
        uses: stCarolas/setup-maven@4.4
        with:
          maven-version: 4.0.0

      - name: Run tests
        run: mvn test -e