name: CI

on:
  push:
    branches:
      - git-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          maven-version: '4.0.0'

      - name: Build with Maven
        run: mvn package --file pom.xml

      - name: Run tests
        run: mvn test --quiet