name: CI

on:
  push:
    branches:
      - git-action

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - "2345:5432"
        env:
          - POSTGRES_USER: postgres
          - POSTGRES_PASSWORD: 2345
          - POSTGRES_DB: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          mvn -B package --no-transfer-progress \
            -Dspring.datasource.url=jdbc:postgresql://localhost:2345/postgres \
            -Dspring.datasource.username=postgres \
            -Dspring.datasource.password=2345

      - name: Run tests
        run: mvn test