name: CI

on:
  push:
    branches:
      - git-action

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      PostgresSQL:
        image: postgres
        ports:
          - "2345:5432"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=2345
          - POSTGRES_DB=postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn package

      - name: Run tests
        run: mvn test